# For more info on HTTP files go to https://aka.ms/vs/httpfile
# API Endpoint
@base_url = http://localhost:7166

### Get unlabeled item
GET {{base_url}}/api/GetUnlabeledItem
Accept: application/json

###

### save label
POST {{base_url}}/api/PostLabel
Content-Type: application/json

{
    "RowId": 4017864,
    "AssociationLevel": 0,
    "Positive": 0,
    "Labeled": true,
    "PartitionKey": "TaggingData",
    "RowKey": "1d34d239-d585-4467-82f0-fca542d92b88",
    "Timestamp": null,
    "ETag": null
}
